"""initial_schema

Revision ID: 20fb5ceb0ab9
Revises: 
Create Date: 2026-07-14 11:09:31.557289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fb5ceb0ab9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('value_rub', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unit_rate_rub', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rates')),
    sa.UniqueConstraint('currency', 'rate_date', 'source', name='uq_exchange_rates_currency_date_source')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rates_rate_date'), ['rate_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_reminder_time', sa.String(length=5), nullable=False),
    sa.Column('default_reminder_offsets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friends_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friends'))
    )
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friends_user_id'), ['user_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('optional_last_four', sa.String(length=4), nullable=True),
    sa.Column('optional_currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_methods_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods'))
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_type', sa.String(length=32), nullable=False),
    sa.Column('billing_interval', sa.Integer(), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('next_charge_date', sa.Date(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('reminder_offsets', sa.JSON(), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('include_owner_in_split', sa.Boolean(), nullable=False),
    sa.Column('split_mode', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_subscriptions_payment_method_id_payment_methods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_next_charge_date'), ['next_charge_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('reminder_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=False),
    sa.Column('reminder_offset', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('unique_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_reminder_deliveries_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminder_deliveries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_deliveries')),
    sa.UniqueConstraint('unique_key', name='uq_reminder_deliveries_unique_key')
    )
    with op.batch_alter_table('reminder_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_deliveries_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_deliveries_user_id'), ['user_id'], unique=False)

    op.create_table('subscription_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('share_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], name=op.f('fk_subscription_participants_friend_id_friends'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_subscription_participants_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_participants'))
    )
    with op.batch_alter_table('subscription_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_participants_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exchange_rate_date', sa.Date(), nullable=True),
    sa.Column('estimated_rub_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_rub_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_rate_estimated', sa.Boolean(), nullable=False),
    sa.Column('conversion_mode', sa.String(length=32), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('split_mode', sa.String(length=32), nullable=True),
    sa.Column('include_owner_in_split', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_transactions_payment_method_id_payment_methods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_transactions_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('debts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('original_share_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('original_share_currency', sa.String(length=3), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], name=op.f('fk_debts_friend_id_friends'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_debts_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_debts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debts'))
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_friend_id'), ['friend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_user_id'), ['user_id'], unique=False)

    op.create_table('transaction_splits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('share_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], name=op.f('fk_transaction_splits_friend_id_friends'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_splits_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_splits'))
    )
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_splits_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_splits_transaction_id'))

    op.drop_table('transaction_splits')
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debts_user_id'))
        batch_op.drop_index(batch_op.f('ix_debts_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_debts_status'))
        batch_op.drop_index(batch_op.f('ix_debts_friend_id'))

    op.drop_table('debts')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))

    op.drop_table('transactions')
    with op.batch_alter_table('subscription_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_participants_subscription_id'))

    op.drop_table('subscription_participants')
    with op.batch_alter_table('reminder_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_deliveries_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_deliveries_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_deliveries_status'))

    op.drop_table('reminder_deliveries')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_next_charge_date'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_user_id'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friends_user_id'))

    op.drop_table('friends')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_user_id'))

    op.drop_table('users')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_exchange_rates_currency'))

    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
